# Generated by Django 3.0.8 on 2020-07-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(db_index=True, max_length=20, unique=True)),
                ('user_password', models.CharField(max_length=20)),
                ('user_role', models.CharField(default='operator', max_length=20)),
            ],
            options={
                'db_table': 'tbl_login_user',
            },
        ),
        migrations.CreateModel(
            name='PricingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_company', models.CharField(default=None, max_length=50)),
                ('mobile_model', models.CharField(default=None, max_length=50)),
                ('repairing_part', models.CharField(default=None, max_length=70)),
                ('repairing_price', models.IntegerField(default=0, null=True)),
                ('repairing_description', models.TextField(default=None, max_length=1000)),
            ],
            options={
                'db_table': 'tbl_repair_pricing',
                'unique_together': {('mobile_company', 'mobile_model', 'repairing_part')},
            },
        ),
    ]
