# Generated by Django 3.0.8 on 2020-07-12 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_phone_number',
            field=models.CharField(default=11111111111, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_real_name',
            field=models.CharField(default=1111111, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_role',
            field=models.CharField(default='consumer', max_length=11),
        ),
    ]
