# Generated by Django 3.0.8 on 2020-07-18 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0006_repairordermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repairordermodel',
            old_name='user',
            new_name='user_phone_number',
        ),
    ]
