# Generated by Django 3.0.8 on 2020-07-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0008_auto_20200719_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairordermodel',
            name='date_item_delivered',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='repairordermodel',
            name='date_item_received',
            field=models.DateTimeField(null=True),
        ),
    ]
