# Generated by Django 3.0.8 on 2020-07-29 20:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0009_auto_20200719_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_real_name', models.CharField(max_length=100)),
                ('user_feedback', models.TextField(default=None, max_length=3000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.UserModel', to_field='user_phone_number')),
            ],
            options={
                'db_table': 'tbl_feedback',
            },
        ),
    ]
