# Generated by Django 3.0.8 on 2020-07-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0010_feedbackmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.ImageField(null=True, upload_to='uploads/', verbose_name='gallery_image')),
                ('mobile_company', models.CharField(default=None, max_length=50)),
                ('mobile_model', models.CharField(default=None, max_length=50)),
            ],
            options={
                'db_table': 'tbl_gallery',
            },
        ),
    ]
