# Generated by Django 3.0.8 on 2020-07-29 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0011_gallerymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(default=None, max_length=50)),
                ('payment_no', models.CharField(default=None, max_length=50)),
                ('amount_paid', models.CharField(default=None, max_length=50)),
                ('order_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.RepairOrderModel')),
            ],
            options={
                'db_table': 'tbl_payment',
            },
        ),
    ]
