# Generated by Django 3.0.8 on 2020-08-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0014_auto_20200730_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='repairordermodel',
            name='user_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='repairordermodel',
            name='user_password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='repairordermodel',
            name='user_real_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
